# Generated by Django 5.0.2 on 2024-02-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('card_id', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('id', 'card_id')},
            },
        ),
    ]
